# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  PYTHON: uv run python
  QUARTO: uv run quarto

tasks:
  default:
    desc: Show available commands
    cmds:
      - task --list
    silent: true

  setup:
    desc: Setup project dependencies
    cmds:
      - uv sync

  clean:
    desc: Clean docs directory
    cmds:
      - rm -rf docs/*
      # Preserve docs directory existence
      - mkdir -p docs 

  build:
    desc: Build all documents to docs/
    cmds:
      - "{{.QUARTO}} render research.qmd"

  preview:
    desc: Start live preview server
    cmds:
      - "{{.QUARTO}} preview"

  check:
    desc: Run project quality checks
    cmds:
      - "{{.QUARTO}} check"
      - "{{.PYTHON}} -m py_compile research.qmd"
